export const mockProducts = [
    {
        id: 1,
        name: 'Pala Pro Carbon',
        description: 'Pala de pádel profesional de carbono, ligera y resistente.',
        type: 'Pala',
        brand: "Nox",
        size: 'Medium',
        image: 'assets/paleta_at10.webp',
        stock: 15,
        quantity: 0,
        price: 249.99,
        offer: 10
    },
    {
        id: 2,
        name: 'Pala Junior',
        description: 'Pala de pádel para niños, ligera y fácil de manejar.',
        type: 'Pala',
        brand: "Nox",
        size: 'Small',
        image: 'assets/paleta_at10.webp',
        stock: 10,
        quantity: 0,
        price: 99.99,
        offer: 0
    },
    {
        id: 3,
        name: 'Pala de Power',
        description: 'Pala de pádel de alta potencia, para jugadores avanzados.',
        type: 'Pala',
        brand: "Nox",
        size: 'Large',
        image: 'assets/paleta_at10.webp',
        stock: 5,
        quantity: 0,
        price: 349.99,
        offer: 0
    },
    {
        id: 4,
        name: 'Pala Pro Carbon',
        description: 'Pala de pádel profesional de carbono, ligera y resistente.',
        type: 'Pala',
        brand: "Nox",
        size: 'Medium',
        image: 'assets/paleta_at10.webp',
        stock: 15,
        quantity: 0,
        price: 249.99,
        offer: 35  

    },
    {
        id: 5,
        name: 'Pala Junior',
        description: 'Pala de pádel para niños, ligera y fácil de manejar.',
        type: 'Pala',
        brand: "Nox",
        size: 'Small',
        image: 'assets/paleta_at10.webp',
        stock: 10,
        quantity: 0,
        price: 99.99,
        offer: 0
    },
    {
        id: 6,
        name: 'Pala de Power',
        description: 'Pala de pádel de alta potencia, para jugadores avanzados.',
        type: 'Pala',
        brand: "Nox",
        size: 'Large',
        image: 'assets/paleta_at10.webp',
        stock: 5,
        quantity: 0,
        price: 349.99,
        offer: 0
    },
    {
        id: 7,
        name: 'Pala Pro Carbon',
        description: 'Pala de pádel profesional de carbono, ligera y resistente.',
        type: 'Pala',
        brand: "Nox",
        size: 'Medium',
        image: 'assets/paleta_at10.webp',
        stock: 15,
        quantity: 0,
        price: 249.99,
        offer: 10
    },
    {
        id: 8,
        name: 'Pala Junior',
        description: 'Pala de pádel para niños, ligera y fácil de manejar.',
        type: 'Pala',
        brand: "Nox",
        size: 'Small',
        image: 'assets/paleta_at10.webp',
        stock: 10,
        quantity: 0,
        price: 99.99,
        offer: 5
    },
    {
        id: 9,
        name: 'Pala de Power',
        description: 'Pala de pádel de alta potencia, para jugadores avanzados.',
        type: 'Pala',
        brand: "Nox",
        size: 'Large',
        image: 'assets/paleta_at10.webp',
        stock: 5,
        quantity: 0,
        price: 349.99,
        offer: 0
    }
];